#! /bin/sh
#
# Install opam, ocaml compilers and standard library.
# From https://github.com/mjambon/setup-ocaml
#
set -eu

mkdir -p .ssh
chmod 700 .ssh

if [ -z "$(git config user.email)" ]; then
  git config --global user.email "docker@example.com"
  git config --global user.name "Docker"
fi

echo -n "opam version: "
opam --version

echo "Initializing opam"
opam init --disable-sandboxing --bare

echo "Building OCaml compilers"
opam switch create "$@"

#echo "Add archive repo"
#opam repo add archive git+https://github.com/ocaml/opam-repository-archive --all-switches


cat >> ~/.bashrc <<"EOF"
# From https://github.com/mjambon/ocaml-layer
echo 'Не забывайте либо запустить "eval $(opam env)", Что инициализирует пути и другие переменные.'
echo 'Или запускать все команды приписывая спереди opam exec --. '
echo "Например:"
echo '  opam exec -- COMMAND'
echo ''
echo
eval $(opam env)
EOF
