#! /usr/bin/env bash
#
# Install opam packages specified on the command line.
# From https://github.com/mjambon/setup-ocaml
#
set -eu

packages=$(echo $* | sed -e 's/,/ /g')
#opam --version
#opam install -y $packages --depext-only &&
opam install -y $packages
opam clean -y
